### ISSUE TITLE
Getting Error from store init on fresh install

### ISSUE THREAD

**Issue by mdevnull** [MrMugame/InstantTwitch#2]
I switched browsers recently and on opera I get an error from a fresh install of the plugin ( opera is just chrome ) coming from here
https://github.com/MrMugame/InstantTwitch/blob/main/src/stores/stores.js#L37

**Comment by MrMugame** [comment]
Mhm interesting, I will look into it. Its time to fix alot the code anyways.

**Comment by MrMugame** [comment]
Issue should be fixed with ff7e2bc and a new release is build
